/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESHPACKET_PB_H_INCLUDED
#define PB_MESHPACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _HardwareModel {
    HardwareModel_UNSET = 0,
    HardwareModel_PRIVATE_HW = 255
} HardwareModel;

typedef enum _Role {
    Role_CLIENT = 0,
    Role_CLIENT_HIDDEN = 8
} Role;

typedef enum _PortNum {
    PortNum_UNKNOWN_APP = 0,
    PortNum_TEXT_MESSAGE_APP = 1,
    PortNum_POSITION_APP = 3,
    PortNum_NODEINFO_APP = 4
} PortNum;

typedef enum _Position_LocSource {
    Position_LocSource_LOC_UNSET = 0,
    Position_LocSource_LOC_MANUAL = 1,
    Position_LocSource_LOC_INTERNAL = 2,
    Position_LocSource_LOC_EXTERNAL = 3
} Position_LocSource;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(240) MeshPacket_encrypted_t;
typedef PB_BYTES_ARRAY_T(32) MeshPacket_public_key_t;
typedef struct _MeshPacket {
    uint32_t from;
    uint32_t to;
    uint8_t channel;
    MeshPacket_encrypted_t encrypted;
    uint32_t id;
    uint32_t rx_time;
    float rx_snr;
    uint8_t hop_limit;
    bool want_ack;
    uint32_t priority;
    int32_t rx_rssi;
    bool via_mqtt;
    uint8_t hop_start;
    MeshPacket_public_key_t public_key;
    bool pki_encrypted;
    uint8_t next_hop;
    uint8_t relay_node;
    uint32_t tx_after;
    uint32_t transport_mechanism;
} MeshPacket;

typedef struct _ServiceEnvelope {
    bool has_packet;
    MeshPacket packet;
    char channel_id[16];
    char gateway_id[10];
} ServiceEnvelope;

typedef struct _Position {
    bool has_latitude_i;
    int32_t latitude_i;
    bool has_longitude_i;
    int32_t longitude_i;
    bool has_altitude;
    int32_t altitude;
    uint32_t time;
    Position_LocSource location_source;
} Position;

typedef struct _User {
    char id[9];
    char long_name[32];
    char short_name[4];
    pb_callback_t macaddr;
    HardwareModel hw_model;
    bool is_licensed;
    Role role;
    pb_callback_t public_key;
    bool has_is_unmessagable;
    bool is_unmessagable;
} User;

typedef PB_BYTES_ARRAY_T(240) Data_payload_t;
typedef struct _Data {
    PortNum portnum;
    Data_payload_t payload;
    bool want_response;
    uint32_t dest;
    uint32_t source;
    uint32_t request_id;
    uint32_t reply_id;
    uint32_t emoji;
    bool has_bitfield;
    uint32_t bitfield;
} Data;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _HardwareModel_MIN HardwareModel_UNSET
#define _HardwareModel_MAX HardwareModel_PRIVATE_HW
#define _HardwareModel_ARRAYSIZE ((HardwareModel)(HardwareModel_PRIVATE_HW+1))

#define _Role_MIN Role_CLIENT
#define _Role_MAX Role_CLIENT_HIDDEN
#define _Role_ARRAYSIZE ((Role)(Role_CLIENT_HIDDEN+1))

#define _PortNum_MIN PortNum_UNKNOWN_APP
#define _PortNum_MAX PortNum_NODEINFO_APP
#define _PortNum_ARRAYSIZE ((PortNum)(PortNum_NODEINFO_APP+1))

#define _Position_LocSource_MIN Position_LocSource_LOC_UNSET
#define _Position_LocSource_MAX Position_LocSource_LOC_EXTERNAL
#define _Position_LocSource_ARRAYSIZE ((Position_LocSource)(Position_LocSource_LOC_EXTERNAL+1))



#define Position_location_source_ENUMTYPE Position_LocSource

#define User_hw_model_ENUMTYPE HardwareModel
#define User_role_ENUMTYPE Role

#define Data_portnum_ENUMTYPE PortNum


/* Initializer values for message structs */
#define MeshPacket_init_default                  {0, 0, 0, {0, {0}}, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, 0, 0, 0, 0}
#define ServiceEnvelope_init_default             {false, MeshPacket_init_default, "", ""}
#define Position_init_default                    {false, 0, false, 0, false, 0, 0, _Position_LocSource_MIN}
#define User_init_default                        {"", "", "", {{NULL}, NULL}, _HardwareModel_MIN, 0, _Role_MIN, {{NULL}, NULL}, false, 0}
#define Data_init_default                        {_PortNum_MIN, {0, {0}}, 0, 0, 0, 0, 0, 0, false, 0}
#define MeshPacket_init_zero                     {0, 0, 0, {0, {0}}, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, 0, 0, 0, 0}
#define ServiceEnvelope_init_zero                {false, MeshPacket_init_zero, "", ""}
#define Position_init_zero                       {false, 0, false, 0, false, 0, 0, _Position_LocSource_MIN}
#define User_init_zero                           {"", "", "", {{NULL}, NULL}, _HardwareModel_MIN, 0, _Role_MIN, {{NULL}, NULL}, false, 0}
#define Data_init_zero                           {_PortNum_MIN, {0, {0}}, 0, 0, 0, 0, 0, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MeshPacket_from_tag                      1
#define MeshPacket_to_tag                        2
#define MeshPacket_channel_tag                   3
#define MeshPacket_encrypted_tag                 5
#define MeshPacket_id_tag                        6
#define MeshPacket_rx_time_tag                   7
#define MeshPacket_rx_snr_tag                    8
#define MeshPacket_hop_limit_tag                 9
#define MeshPacket_want_ack_tag                  10
#define MeshPacket_priority_tag                  11
#define MeshPacket_rx_rssi_tag                   12
#define MeshPacket_via_mqtt_tag                  14
#define MeshPacket_hop_start_tag                 15
#define MeshPacket_public_key_tag                16
#define MeshPacket_pki_encrypted_tag             17
#define MeshPacket_next_hop_tag                  18
#define MeshPacket_relay_node_tag                19
#define MeshPacket_tx_after_tag                  20
#define MeshPacket_transport_mechanism_tag       21
#define ServiceEnvelope_packet_tag               1
#define ServiceEnvelope_channel_id_tag           2
#define ServiceEnvelope_gateway_id_tag           3
#define Position_latitude_i_tag                  1
#define Position_longitude_i_tag                 2
#define Position_altitude_tag                    3
#define Position_time_tag                        4
#define Position_location_source_tag             5
#define User_id_tag                              1
#define User_long_name_tag                       2
#define User_short_name_tag                      3
#define User_macaddr_tag                         4
#define User_hw_model_tag                        5
#define User_is_licensed_tag                     6
#define User_role_tag                            7
#define User_public_key_tag                      8
#define User_is_unmessagable_tag                 9
#define Data_portnum_tag                         1
#define Data_payload_tag                         2
#define Data_want_response_tag                   3
#define Data_dest_tag                            4
#define Data_source_tag                          5
#define Data_request_id_tag                      6
#define Data_reply_id_tag                        7
#define Data_emoji_tag                           8
#define Data_bitfield_tag                        9

/* Struct field encoding specification for nanopb */
#define MeshPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  from,              1) \
X(a, STATIC,   SINGULAR, FIXED32,  to,                2) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           3) \
X(a, STATIC,   SINGULAR, BYTES,    encrypted,         5) \
X(a, STATIC,   SINGULAR, FIXED32,  id,                6) \
X(a, STATIC,   SINGULAR, FIXED32,  rx_time,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    rx_snr,            8) \
X(a, STATIC,   SINGULAR, UINT32,   hop_limit,         9) \
X(a, STATIC,   SINGULAR, BOOL,     want_ack,         10) \
X(a, STATIC,   SINGULAR, UINT32,   priority,         11) \
X(a, STATIC,   SINGULAR, INT32,    rx_rssi,          12) \
X(a, STATIC,   SINGULAR, BOOL,     via_mqtt,         14) \
X(a, STATIC,   SINGULAR, UINT32,   hop_start,        15) \
X(a, STATIC,   SINGULAR, BYTES,    public_key,       16) \
X(a, STATIC,   SINGULAR, BOOL,     pki_encrypted,    17) \
X(a, STATIC,   SINGULAR, UINT32,   next_hop,         18) \
X(a, STATIC,   SINGULAR, UINT32,   relay_node,       19) \
X(a, STATIC,   SINGULAR, UINT32,   tx_after,         20) \
X(a, STATIC,   SINGULAR, UINT32,   transport_mechanism,  21)
#define MeshPacket_CALLBACK NULL
#define MeshPacket_DEFAULT NULL

#define ServiceEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  packet,            1) \
X(a, STATIC,   SINGULAR, STRING,   channel_id,        2) \
X(a, STATIC,   SINGULAR, STRING,   gateway_id,        3)
#define ServiceEnvelope_CALLBACK NULL
#define ServiceEnvelope_DEFAULT NULL
#define ServiceEnvelope_packet_MSGTYPE MeshPacket

#define Position_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SFIXED32, latitude_i,        1) \
X(a, STATIC,   OPTIONAL, SFIXED32, longitude_i,       2) \
X(a, STATIC,   OPTIONAL, INT32,    altitude,          3) \
X(a, STATIC,   SINGULAR, FIXED32,  time,              4) \
X(a, STATIC,   SINGULAR, UENUM,    location_source,   5)
#define Position_CALLBACK NULL
#define Position_DEFAULT NULL

#define User_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   long_name,         2) \
X(a, STATIC,   SINGULAR, STRING,   short_name,        3) \
X(a, CALLBACK, SINGULAR, BYTES,    macaddr,           4) \
X(a, STATIC,   SINGULAR, UENUM,    hw_model,          5) \
X(a, STATIC,   SINGULAR, BOOL,     is_licensed,       6) \
X(a, STATIC,   SINGULAR, UENUM,    role,              7) \
X(a, CALLBACK, SINGULAR, BYTES,    public_key,        8) \
X(a, STATIC,   OPTIONAL, BOOL,     is_unmessagable,   9)
#define User_CALLBACK pb_default_field_callback
#define User_DEFAULT NULL

#define Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    portnum,           1) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           2) \
X(a, STATIC,   SINGULAR, BOOL,     want_response,     3) \
X(a, STATIC,   SINGULAR, FIXED32,  dest,              4) \
X(a, STATIC,   SINGULAR, FIXED32,  source,            5) \
X(a, STATIC,   SINGULAR, FIXED32,  request_id,        6) \
X(a, STATIC,   SINGULAR, FIXED32,  reply_id,          7) \
X(a, STATIC,   SINGULAR, FIXED32,  emoji,             8) \
X(a, STATIC,   OPTIONAL, UINT32,   bitfield,          9)
#define Data_CALLBACK NULL
#define Data_DEFAULT NULL

extern const pb_msgdesc_t MeshPacket_msg;
extern const pb_msgdesc_t ServiceEnvelope_msg;
extern const pb_msgdesc_t Position_msg;
extern const pb_msgdesc_t User_msg;
extern const pb_msgdesc_t Data_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MeshPacket_fields &MeshPacket_msg
#define ServiceEnvelope_fields &ServiceEnvelope_msg
#define Position_fields &Position_msg
#define User_fields &User_msg
#define Data_fields &Data_msg

/* Maximum encoded size of messages (where known) */
/* User_size depends on runtime parameters */
#define Data_size                                278
#define MESHPACKET_PB_H_MAX_SIZE                 ServiceEnvelope_size
#define MeshPacket_size                          358
#define Position_size                            28
#define ServiceEnvelope_size                     389

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
