/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "meshpacket.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MeshPacket, MeshPacket, 2)


PB_BIND(ServiceEnvelope, ServiceEnvelope, 2)


PB_BIND(Position, Position, AUTO)


PB_BIND(User, User, AUTO)


PB_BIND(Data, Data, 2)











